package OtherComponents;

import DesignPatterns.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kyle
 */
public class MainMenu extends javax.swing.JFrame implements Close {
    
    
    private static User user;
    private DecisionNoStrategy NoPrefer = new DecisionNoStrategy();
    private DecisionNoStrategy bought = new ShowBoughtLotSubClass();
    private DecisionNoStrategy reserved = new ShowReservedLotSubClass();
    private DecisionYesStrategy YesPrefer = new DecisionYesStrategy();
    
    
    /**
     * Creates new form MainMenu
     * @param user
     */
    public MainMenu(User user) {
        MainMenu.user=user;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelSearchBtn1 = new javax.swing.JPanel();
        jLabelShowSearchLots = new javax.swing.JLabel();
        jPanelSearchBtn = new javax.swing.JPanel();
        jLabelSearchLot = new javax.swing.JLabel();
        jPanelResLotBtn = new javax.swing.JPanel();
        jLabelBuyReserved = new javax.swing.JLabel();
        jPanelSellLotBtn = new javax.swing.JPanel();
        jLabelSellLot = new javax.swing.JLabel();
        jPanelExitBtn = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLayeredPaneMain = new javax.swing.JLayeredPane();
        jPanelShowLots = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLayeredPaneShowLot = new javax.swing.JLayeredPane();
        jPanelShowLotSmall = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableReserveShowLot = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableBoughtShowLot = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelSearchLot = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButtonPreferYes = new javax.swing.JButton();
        jButtonPreferNo = new javax.swing.JButton();
        jLayeredPaneSearchTable = new javax.swing.JLayeredPane();
        jPanelPrefNo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrefNo = new javax.swing.JTable();
        jPanelReserveLotPreferNo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldReserveLotIDPreferNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ChosenLotBtnPreferNo = new javax.swing.JButton();
        jPanelPrefYes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePrefYes = new javax.swing.JTable();
        jComboBoxLotSize = new javax.swing.JComboBox<>();
        jTextFieldLotSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldLotBlock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxPrice = new javax.swing.JComboBox<>();
        jTextFieldPrice = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jPanelReserveLot = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldReserveLotIDPreferYes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ChosenLotBtnPreferYes = new javax.swing.JButton();
        jPanelNoLaman = new javax.swing.JPanel();
        jPanelBuyLot = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelBuyLotSmall = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBuyNow = new javax.swing.JTable();
        jButtonBuyReservedLot = new javax.swing.JButton();
        jPanelSellLot = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLayeredPaneSellLot = new javax.swing.JLayeredPane();
        jPanelSellLotSmall = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableSellLot = new javax.swing.JTable();
        jPanelReserveLotPreferNo2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldSellLot = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ChosenLotBtnSellLot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelTitle.setBackground(new java.awt.Color(218, 41, 28));
        jPanelTitle.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("REAL ESTATE SYSTEM");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setText("REAL ESTATE SYSTEM");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTitleLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2)
                    .addContainerGap(383, Short.MAX_VALUE)))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTitleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.setBackground(new java.awt.Color(224, 187, 87));

        jPanelSearchBtn1.setBackground(new java.awt.Color(134, 112, 52));

        jLabelShowSearchLots.setBackground(new java.awt.Color(134, 112, 52));
        jLabelShowSearchLots.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelShowSearchLots.setForeground(new java.awt.Color(255, 255, 255));
        jLabelShowSearchLots.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelShowSearchLots.setText("Show Owned/Reserved Lots");
        jLabelShowSearchLots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelShowSearchLotsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchBtn1Layout = new javax.swing.GroupLayout(jPanelSearchBtn1);
        jPanelSearchBtn1.setLayout(jPanelSearchBtn1Layout);
        jPanelSearchBtn1Layout.setHorizontalGroup(
            jPanelSearchBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelShowSearchLots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSearchBtn1Layout.setVerticalGroup(
            jPanelSearchBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelShowSearchLots, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelSearchBtn.setBackground(new java.awt.Color(134, 112, 52));

        jLabelSearchLot.setBackground(new java.awt.Color(134, 112, 52));
        jLabelSearchLot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSearchLot.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearchLot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSearchLot.setText("Search/Reserve Lots");
        jLabelSearchLot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSearchLotMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchBtnLayout = new javax.swing.GroupLayout(jPanelSearchBtn);
        jPanelSearchBtn.setLayout(jPanelSearchBtnLayout);
        jPanelSearchBtnLayout.setHorizontalGroup(
            jPanelSearchBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearchLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSearchBtnLayout.setVerticalGroup(
            jPanelSearchBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSearchLot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelResLotBtn.setBackground(new java.awt.Color(134, 112, 52));

        jLabelBuyReserved.setBackground(new java.awt.Color(134, 112, 52));
        jLabelBuyReserved.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBuyReserved.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBuyReserved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuyReserved.setText("Buy Reserved Lots");
        jLabelBuyReserved.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuyReservedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelResLotBtnLayout = new javax.swing.GroupLayout(jPanelResLotBtn);
        jPanelResLotBtn.setLayout(jPanelResLotBtnLayout);
        jPanelResLotBtnLayout.setHorizontalGroup(
            jPanelResLotBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResLotBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuyReserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelResLotBtnLayout.setVerticalGroup(
            jPanelResLotBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBuyReserved, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelSellLotBtn.setBackground(new java.awt.Color(134, 112, 52));

        jLabelSellLot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSellLot.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSellLot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSellLot.setText("Sell Owned Lots");
        jLabelSellLot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSellLotMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSellLotBtnLayout = new javax.swing.GroupLayout(jPanelSellLotBtn);
        jPanelSellLotBtn.setLayout(jPanelSellLotBtnLayout);
        jPanelSellLotBtnLayout.setHorizontalGroup(
            jPanelSellLotBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSellLotBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSellLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSellLotBtnLayout.setVerticalGroup(
            jPanelSellLotBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSellLot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelExitBtn.setBackground(new java.awt.Color(134, 112, 52));

        jLabelExit.setBackground(new java.awt.Color(255, 255, 255));
        jLabelExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("Exit");
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelExitBtnLayout = new javax.swing.GroupLayout(jPanelExitBtn);
        jPanelExitBtn.setLayout(jPanelExitBtnLayout);
        jPanelExitBtnLayout.setHorizontalGroup(
            jPanelExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelExitBtnLayout.setVerticalGroup(
            jPanelExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelExit, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelResLotBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSellLotBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSearchBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearchBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelResLotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSellLotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPaneMain.setLayout(new java.awt.CardLayout());

        jPanelShowLots.setBackground(new java.awt.Color(84, 86, 91));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Show Lots");

        jLayeredPaneShowLot.setLayout(new java.awt.CardLayout());

        jTableReserveShowLot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lot ID", "Lot Size( Sq. Meters)", "Lot Block", "Lot Number", "Lot Price (Pesos)", "Lot Status"
            }
        ));
        jScrollPane6.setViewportView(jTableReserveShowLot);

        jTableBoughtShowLot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lot ID", "Lot Size( Sq. Meters)", "Lot Block", "Lot Number", "Lot Price (Pesos)", "Lot Status"
            }
        ));
        jScrollPane7.setViewportView(jTableBoughtShowLot);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Reserved Lots");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Bought Lots");

        javax.swing.GroupLayout jPanelShowLotSmallLayout = new javax.swing.GroupLayout(jPanelShowLotSmall);
        jPanelShowLotSmall.setLayout(jPanelShowLotSmallLayout);
        jPanelShowLotSmallLayout.setHorizontalGroup(
            jPanelShowLotSmallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowLotSmallLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShowLotSmallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addGroup(jPanelShowLotSmallLayout.createSequentialGroup()
                        .addGroup(jPanelShowLotSmallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelShowLotSmallLayout.setVerticalGroup(
            jPanelShowLotSmallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowLotSmallLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPaneShowLot.add(jPanelShowLotSmall, "card4");

        javax.swing.GroupLayout jPanelShowLotsLayout = new javax.swing.GroupLayout(jPanelShowLots);
        jPanelShowLots.setLayout(jPanelShowLotsLayout);
        jPanelShowLotsLayout.setHorizontalGroup(
            jPanelShowLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShowLotsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShowLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPaneShowLot)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelShowLotsLayout.setVerticalGroup(
            jPanelShowLotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowLotsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPaneShowLot)
                .addContainerGap())
        );

        jLayeredPaneMain.add(jPanelShowLots, "card4");

        jPanelSearchLot.setBackground(new java.awt.Color(84, 86, 91));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Search Lots");

        jButtonPreferYes.setText("Preferred Specs");
        jButtonPreferYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreferYesActionPerformed(evt);
            }
        });

        jButtonPreferNo.setText("No Preferred Specs");
        jButtonPreferNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreferNoActionPerformed(evt);
            }
        });

        jLayeredPaneSearchTable.setLayout(new java.awt.CardLayout());

        jTablePrefNo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lot ID", "Lot Size( Sq. Meters)", "Lot Block", "Lot Number", "Lot Price (Pesos)", "Lot Status"
            }
        ));
        jScrollPane1.setViewportView(jTablePrefNo);

        jPanelReserveLotPreferNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Already Chosen a Lot?");

        jTextFieldReserveLotIDPreferNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldReserveLotIDPreferNoActionPerformed(evt);
            }
        });

        jLabel10.setText("Enter Lot ID");

        ChosenLotBtnPreferNo.setText("ENTER");
        ChosenLotBtnPreferNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChosenLotBtnPreferNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReserveLotPreferNoLayout = new javax.swing.GroupLayout(jPanelReserveLotPreferNo);
        jPanelReserveLotPreferNo.setLayout(jPanelReserveLotPreferNoLayout);
        jPanelReserveLotPreferNoLayout.setHorizontalGroup(
            jPanelReserveLotPreferNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReserveLotPreferNoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReserveLotPreferNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReserveLotPreferNoLayout.createSequentialGroup()
                        .addGroup(jPanelReserveLotPreferNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelReserveLotPreferNoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldReserveLotIDPreferNo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ChosenLotBtnPreferNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelReserveLotPreferNoLayout.setVerticalGroup(
            jPanelReserveLotPreferNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReserveLotPreferNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReserveLotPreferNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldReserveLotIDPreferNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(ChosenLotBtnPreferNo)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPrefNoLayout = new javax.swing.GroupLayout(jPanelPrefNo);
        jPanelPrefNo.setLayout(jPanelPrefNoLayout);
        jPanelPrefNoLayout.setHorizontalGroup(
            jPanelPrefNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrefNoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrefNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelPrefNoLayout.createSequentialGroup()
                        .addGap(0, 551, Short.MAX_VALUE)
                        .addComponent(jPanelReserveLotPreferNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelPrefNoLayout.setVerticalGroup(
            jPanelPrefNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrefNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelReserveLotPreferNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPaneSearchTable.add(jPanelPrefNo, "card4");

        jTablePrefYes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lot ID", "Lot Size (Sq. Meters)", "Lot Block", "Lot Number", "Lot Price (Pesos)", "Lot Status"
            }
        ));
        jScrollPane2.setViewportView(jTablePrefYes);

        jComboBoxLotSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">=", "<=" }));

        jTextFieldLotSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLotSizeActionPerformed(evt);
            }
        });

        jLabel3.setText("Lot Size (50 - 255)");

        jLabel4.setText("Lot Block Number (1 - 5)");

        jTextFieldLotBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLotBlockActionPerformed(evt);
            }
        });

        jLabel5.setText("Price (100,000 - 4,500,000)");

        jComboBoxPrice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">=", "<=" }));
        jComboBoxPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPriceActionPerformed(evt);
            }
        });

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        jPanelReserveLot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Already Chosen a Lot?");

        jLabel8.setText("Enter Lot ID");

        ChosenLotBtnPreferYes.setText("ENTER");
        ChosenLotBtnPreferYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChosenLotBtnPreferYesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReserveLotLayout = new javax.swing.GroupLayout(jPanelReserveLot);
        jPanelReserveLot.setLayout(jPanelReserveLotLayout);
        jPanelReserveLotLayout.setHorizontalGroup(
            jPanelReserveLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReserveLotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReserveLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReserveLotLayout.createSequentialGroup()
                        .addGroup(jPanelReserveLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelReserveLotLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldReserveLotIDPreferYes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ChosenLotBtnPreferYes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelReserveLotLayout.setVerticalGroup(
            jPanelReserveLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReserveLotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReserveLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldReserveLotIDPreferYes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(ChosenLotBtnPreferYes)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPrefYesLayout = new javax.swing.GroupLayout(jPanelPrefYes);
        jPanelPrefYes.setLayout(jPanelPrefYesLayout);
        jPanelPrefYesLayout.setHorizontalGroup(
            jPanelPrefYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrefYesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrefYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelPrefYesLayout.createSequentialGroup()
                        .addGroup(jPanelPrefYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanelPrefYesLayout.createSequentialGroup()
                                .addComponent(jComboBoxLotSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLotSize, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanelPrefYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrefYesLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addComponent(jTextFieldLotBlock))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPrefYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(jPanelPrefYesLayout.createSequentialGroup()
                                .addComponent(jComboBoxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPrice)))
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtn)
                        .addGap(66, 66, 66)
                        .addComponent(jPanelReserveLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelPrefYesLayout.setVerticalGroup(
            jPanelPrefYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrefYesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrefYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelReserveLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrefYesLayout.createSequentialGroup()
                        .addGroup(jPanelPrefYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPrefYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxLotSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLotSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLotBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPaneSearchTable.add(jPanelPrefYes, "card2");

        javax.swing.GroupLayout jPanelNoLamanLayout = new javax.swing.GroupLayout(jPanelNoLaman);
        jPanelNoLaman.setLayout(jPanelNoLamanLayout);
        jPanelNoLamanLayout.setHorizontalGroup(
            jPanelNoLamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanelNoLamanLayout.setVerticalGroup(
            jPanelNoLamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jLayeredPaneSearchTable.add(jPanelNoLaman, "card3");

        javax.swing.GroupLayout jPanelSearchLotLayout = new javax.swing.GroupLayout(jPanelSearchLot);
        jPanelSearchLot.setLayout(jPanelSearchLotLayout);
        jPanelSearchLotLayout.setHorizontalGroup(
            jPanelSearchLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchLotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPaneSearchTable)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSearchLotLayout.createSequentialGroup()
                        .addComponent(jButtonPreferYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPreferNo))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSearchLotLayout.setVerticalGroup(
            jPanelSearchLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanelSearchLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPreferYes)
                    .addComponent(jButtonPreferNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPaneSearchTable)
                .addContainerGap())
        );

        jLayeredPaneMain.add(jPanelSearchLot, "card4");

        jPanelBuyLot.setBackground(new java.awt.Color(84, 86, 91));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Buy Reserved Lots");

        jTableBuyNow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lot ID", "Lot Size( Sq. Meters)", "Lot Block", "Lot Number", "Lot Price (Pesos)", "Lot Status"
            }
        ));
        jScrollPane3.setViewportView(jTableBuyNow);

        javax.swing.GroupLayout jPanelBuyLotSmallLayout = new javax.swing.GroupLayout(jPanelBuyLotSmall);
        jPanelBuyLotSmall.setLayout(jPanelBuyLotSmallLayout);
        jPanelBuyLotSmallLayout.setHorizontalGroup(
            jPanelBuyLotSmallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        jPanelBuyLotSmallLayout.setVerticalGroup(
            jPanelBuyLotSmallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        jButtonBuyReservedLot.setText("BUY NOW");
        jButtonBuyReservedLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyReservedLotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuyLotLayout = new javax.swing.GroupLayout(jPanelBuyLot);
        jPanelBuyLot.setLayout(jPanelBuyLotLayout);
        jPanelBuyLotLayout.setHorizontalGroup(
            jPanelBuyLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuyLotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuyLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addGroup(jPanelBuyLotLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jButtonBuyReservedLot)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelBuyLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBuyLotLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelBuyLotSmall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelBuyLotLayout.setVerticalGroup(
            jPanelBuyLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuyLotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuyReservedLot)
                .addContainerGap(738, Short.MAX_VALUE))
            .addGroup(jPanelBuyLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuyLotLayout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(jPanelBuyLotSmall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jLayeredPaneMain.add(jPanelBuyLot, "card3");

        jPanelSellLot.setBackground(new java.awt.Color(84, 86, 91));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Search Lots");

        jLayeredPaneSellLot.setLayout(new java.awt.CardLayout());

        jTableSellLot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lot ID", "Lot Size( Sq. Meters)", "Lot Block", "Lot Number", "Lot Price (Pesos)", "Lot Status"
            }
        ));
        jScrollPane5.setViewportView(jTableSellLot);

        jPanelReserveLotPreferNo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Already Chosen a Lot?");

        jTextFieldSellLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSellLotActionPerformed(evt);
            }
        });

        jLabel17.setText("Enter Lot ID");

        ChosenLotBtnSellLot.setText("ENTER");
        ChosenLotBtnSellLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChosenLotBtnSellLotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReserveLotPreferNo2Layout = new javax.swing.GroupLayout(jPanelReserveLotPreferNo2);
        jPanelReserveLotPreferNo2.setLayout(jPanelReserveLotPreferNo2Layout);
        jPanelReserveLotPreferNo2Layout.setHorizontalGroup(
            jPanelReserveLotPreferNo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReserveLotPreferNo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReserveLotPreferNo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReserveLotPreferNo2Layout.createSequentialGroup()
                        .addGroup(jPanelReserveLotPreferNo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelReserveLotPreferNo2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSellLot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ChosenLotBtnSellLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelReserveLotPreferNo2Layout.setVerticalGroup(
            jPanelReserveLotPreferNo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReserveLotPreferNo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReserveLotPreferNo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSellLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(ChosenLotBtnSellLot)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelSellLotSmallLayout = new javax.swing.GroupLayout(jPanelSellLotSmall);
        jPanelSellLotSmall.setLayout(jPanelSellLotSmallLayout);
        jPanelSellLotSmallLayout.setHorizontalGroup(
            jPanelSellLotSmallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSellLotSmallLayout.createSequentialGroup()
                .addGroup(jPanelSellLotSmallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSellLotSmallLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelReserveLotPreferNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelSellLotSmallLayout.setVerticalGroup(
            jPanelSellLotSmallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSellLotSmallLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelReserveLotPreferNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPaneSellLot.add(jPanelSellLotSmall, "card4");

        javax.swing.GroupLayout jPanelSellLotLayout = new javax.swing.GroupLayout(jPanelSellLot);
        jPanelSellLot.setLayout(jPanelSellLotLayout);
        jPanelSellLotLayout.setHorizontalGroup(
            jPanelSellLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSellLotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSellLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPaneSellLot)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSellLotLayout.setVerticalGroup(
            jPanelSellLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSellLotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPaneSellLot)
                .addContainerGap())
        );

        jLayeredPaneMain.add(jPanelSellLot, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPaneMain))
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPaneMain)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBuyReservedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuyReservedMouseClicked
        try {
            switchPanels(jPanelBuyLot, jLayeredPaneMain);
            DBComponents db = DBComponents.getInstance();
            db.getCon();
            resetTable(jTableBuyNow);
            reserved.showTable(db, user, jTableBuyNow);
        } catch (Exception e) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }//GEN-LAST:event_jLabelBuyReservedMouseClicked

    private void jLabelSearchLotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchLotMouseClicked
        switchPanels(jPanelSearchLot, jLayeredPaneMain);
        switchPanels(jPanelNoLaman, jLayeredPaneSearchTable);
        
    }//GEN-LAST:event_jLabelSearchLotMouseClicked

    private void jLabelSellLotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSellLotMouseClicked
        try {
            switchPanels(jPanelSellLot, jLayeredPaneMain);
            DBComponents db = DBComponents.getInstance();
            db.getCon();
            bought.showTable(db,user,jTableSellLot);//ShowBoughtLots
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelSellLotMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Are you Sure you Want to Exit?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION){
          close();  
        }
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jButtonPreferYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreferYesActionPerformed
        switchPanels(jPanelPrefYes, jLayeredPaneSearchTable);
    }//GEN-LAST:event_jButtonPreferYesActionPerformed

    private void jButtonPreferNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreferNoActionPerformed
        try {
            //Singleton Pattern
            DBComponents db = DBComponents.getInstance();
            db.getCon();
            NoPrefer.showTable(db,user, jTablePrefNo);
            switchPanels(jPanelPrefNo, jLayeredPaneSearchTable);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPreferNoActionPerformed

    private void jTextFieldLotBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLotBlockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLotBlockActionPerformed

    private void jComboBoxPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPriceActionPerformed

    private void jTextFieldLotSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLotSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLotSizeActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed

        try {
            user.getLot().setSize(Integer.parseInt(jTextFieldLotSize.getText()));
            user.getLot().setBlock(Integer.parseInt(jTextFieldLotBlock.getText()));
            user.getLot().setPrice(Integer.parseInt(jTextFieldPrice.getText()));
            
            DBComponents db = DBComponents.getInstance();
            db.getCon();
            YesPrefer.showTable(db,user,jTablePrefYes);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void ChosenLotBtnPreferYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChosenLotBtnPreferYesActionPerformed

        try {
            user.getLot().setSize(Integer.parseInt(jTextFieldLotSize.getText()));
            user.getLot().setBlock(Integer.parseInt(jTextFieldLotBlock.getText()));
            user.getLot().setPrice(Integer.parseInt(jTextFieldPrice.getText()));
            YesPrefer.setComboBoxLotSize(jComboBoxLotSize.getSelectedIndex());
            YesPrefer.setComboBoxLotPrice(jComboBoxPrice.getSelectedIndex());
            
            user.getLot().setId(Integer.parseInt(jTextFieldReserveLotIDPreferYes.getText()));
            DBComponents db = DBComponents.getInstance();
            db.getCon();
            YesPrefer.ReserveLot(db, user, jTablePrefYes);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ChosenLotBtnPreferYesActionPerformed

    private void jTextFieldReserveLotIDPreferNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldReserveLotIDPreferNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldReserveLotIDPreferNoActionPerformed

    private void jButtonBuyReservedLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyReservedLotActionPerformed
        UserLotAction buy = new UserLotActionBuyStrategy(reserved);
        try {
            int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to buy the specified Lots?", "Confirmation", JOptionPane.YES_NO_OPTION);
            DBComponents db = DBComponents.getInstance();
            db.getCon();
            if (result == JOptionPane.YES_OPTION){
                buy.LotAction(db, user, jTablePrefNo);
                resetTable(jTableBuyNow);
                reserved.showTable(db,user,jTableBuyNow);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuyReservedLotActionPerformed

    private void jLabelShowSearchLotsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShowSearchLotsMouseClicked
        try {
            switchPanels(jPanelShowLots, jLayeredPaneMain);
            DBComponents db = DBComponents.getInstance();
            db.getCon();
            bought.showTable(db,user,jTableBoughtShowLot);//showBought Lots by user
            reserved.showTable(db, user, jTableReserveShowLot);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabelShowSearchLotsMouseClicked

    private void ChosenLotBtnSellLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChosenLotBtnSellLotActionPerformed
        UserLotAction sell = new UserLotActionSellStrategy(bought);
        
        try {
            user.getLot().setId(Integer.parseInt(jTextFieldSellLot.getText()));
            int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to sell that Lot?", "Confirmation", JOptionPane.YES_NO_OPTION);
            DBComponents db = DBComponents.getInstance();
            db.getCon();
            if (result == JOptionPane.YES_OPTION){
                sell.LotAction(db, user, jTableSellLot);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ChosenLotBtnSellLotActionPerformed

    private void jTextFieldSellLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSellLotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSellLotActionPerformed

    private void ChosenLotBtnPreferNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChosenLotBtnPreferNoActionPerformed
        try {
            user.getLot().setId(Integer.parseInt(jTextFieldReserveLotIDPreferNo.getText()));
            DBComponents db = DBComponents.getInstance();
            db.getCon();
            NoPrefer.ReserveLot(db, user, jTablePrefNo);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ChosenLotBtnPreferNoActionPerformed

    @Override
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void switchPanels(JPanel panel, JLayeredPane layeredPane){
        layeredPane.removeAll();
        layeredPane.add(panel);
        layeredPane.repaint();
        layeredPane.revalidate();
    }
    
    public void resetTable(JTable jtable1){
        DefaultTableModel tb1Model = (DefaultTableModel)jtable1.getModel();
        tb1Model.setRowCount(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChosenLotBtnPreferNo;
    private javax.swing.JButton ChosenLotBtnPreferYes;
    private javax.swing.JButton ChosenLotBtnSellLot;
    private javax.swing.JButton SearchBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBuyReservedLot;
    private javax.swing.JButton jButtonPreferNo;
    private javax.swing.JButton jButtonPreferYes;
    private javax.swing.JComboBox<String> jComboBoxLotSize;
    private javax.swing.JComboBox<String> jComboBoxPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBuyReserved;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelSearchLot;
    private javax.swing.JLabel jLabelSellLot;
    private javax.swing.JLabel jLabelShowSearchLots;
    private javax.swing.JLayeredPane jLayeredPaneMain;
    private javax.swing.JLayeredPane jLayeredPaneSearchTable;
    private javax.swing.JLayeredPane jLayeredPaneSellLot;
    private javax.swing.JLayeredPane jLayeredPaneShowLot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBuyLot;
    private javax.swing.JPanel jPanelBuyLotSmall;
    private javax.swing.JPanel jPanelExitBtn;
    private javax.swing.JPanel jPanelNoLaman;
    private javax.swing.JPanel jPanelPrefNo;
    private javax.swing.JPanel jPanelPrefYes;
    private javax.swing.JPanel jPanelResLotBtn;
    private javax.swing.JPanel jPanelReserveLot;
    private javax.swing.JPanel jPanelReserveLotPreferNo;
    private javax.swing.JPanel jPanelReserveLotPreferNo2;
    private javax.swing.JPanel jPanelSearchBtn;
    private javax.swing.JPanel jPanelSearchBtn1;
    private javax.swing.JPanel jPanelSearchLot;
    private javax.swing.JPanel jPanelSellLot;
    private javax.swing.JPanel jPanelSellLotBtn;
    private javax.swing.JPanel jPanelSellLotSmall;
    private javax.swing.JPanel jPanelShowLotSmall;
    private javax.swing.JPanel jPanelShowLots;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableBoughtShowLot;
    private javax.swing.JTable jTableBuyNow;
    private javax.swing.JTable jTablePrefNo;
    private javax.swing.JTable jTablePrefYes;
    private javax.swing.JTable jTableReserveShowLot;
    private javax.swing.JTable jTableSellLot;
    private javax.swing.JTextField jTextFieldLotBlock;
    private javax.swing.JTextField jTextFieldLotSize;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldReserveLotIDPreferNo;
    private javax.swing.JTextField jTextFieldReserveLotIDPreferYes;
    private javax.swing.JTextField jTextFieldSellLot;
    // End of variables declaration//GEN-END:variables
}
